---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.13.0
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(dplyr)
library(tidyverse)
library(factoextra)
library(sf)
options(repr.matrix.max.cols=100, repr.matrix.max.rows=100)
```

# 物种丰富度

```{r}
china_map <- st_read("../chinese_terrestral//SHP//China_map.shp")
grid <- st_read("../chinese_terrestral//input//grid.shp")
south_ocean <- st_read("../chinese_terrestral//input//China-9-1.shp") %>% st_transform(crs = st_crs(grid))
# boundary <- st_read('../chinese_terrestral//SHP//boundary_of_realms.shp')
# gubei <- st_read('../chinese_terrestral//SHP/gubei_dongyang.shp')
phyloregions_line <- st_read('../chinese_terrestral//SHP//phyloregions_divider.shp') %>% within({divider=as.factor(divider)})
```

```{r}
# calculate species richness
chinese_wild_life_list <- read.csv('../chinese_terrestral/chinese_wildlife_list/taxonomy.csv') %>% 
                        select('scientificName','kingdomName','phylumName','className','orderName','familyName')
Chinese_species_distribution_grid <- read.csv("../chinese_terrestral//species_distribution_grid_filtered.csv",
                                              header = F, col.names = c("class","species","grid_id","area")) %>% 
                                            group_by(class,species,grid_id) %>% summarise(area = sum(area)) %>% ungroup() %>%
                                                filter(class == 'ave') %>% 
                                            left_join(chinese_wild_life_list,by = c('species' = 'scientificName')) %>% 
                                            filter(!(familyName %in% toupper(c('Procellariidae','Alcidae','Fregatidae','Gaviidae','Phaethontidae','Diomedeidae',
                                               'Stercorariidae','Sulidae','Pelecanidae','Phalacrocoracidae','Laridae','Hydrobatidae')))) %>% 
                                            select("class","species","grid_id")

Chinese_species_distribution_grid$species %>% unique() %>% length()
aves <- group_by(Chinese_species_distribution_grid,grid_id) %>% summarize(richness = length(unique(species)))
map <- left_join(aves,grid,by = c('grid_id'='id'))

options(repr.plot.width=12, repr.plot.height=10)
ggplot()+geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = map,aes(fill = richness,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=divider,size = divider))+
    scale_color_manual(values = c('grey60','red','#F75404'),guide = "none")+ # delete legends of divider
    scale_size_manual(values = c(0.5,0.8,0.6),guide = "none")+
    ggtitle("richness")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5),
         legend.position = c(0.13,0.2),
         legend.key.size = unit(18, "pt"),
         legend.title=element_text(size=13),
         legend.text=element_text(size=10))
ggsave('bird_species_richness.tiff',height = 7,width = 7,units = 'in',dpi=300)
```

# 数据整合


## 加载数据

```{r}
bird_trait_data_ecography <- read.csv("bird_trait_data_ecography.csv",header = T) %>% 
                            select(Species,iucn_2021_binomial,Habitat_specificity)
Chinesebirdsdata <- read.csv('Chinesebirdsdata/Chinesebirdsdata.csv')
Chinesebirdsdata <- left_join(Chinesebirdsdata,bird_trait_data_ecography,by = 'iucn_2021_binomial')
Chinesebirdsdata <- within(Chinesebirdsdata,{
    male_mass_max_g <- ifelse(is.na(male_mass_max_g),male_mass_min_g,male_mass_max_g)
    female_mass_max_g <- ifelse(is.na(female_mass_max_g),female_mass_min_g,female_mass_max_g)
    male_size_max_mm <- ifelse(is.na(male_size_max_mm),male_size_min_mm,male_size_max_mm)
    female_size_max_mm <- ifelse(is.na(female_size_max_mm),female_size_min_mm,female_size_max_mm)
    clutch_size_max <- ifelse(is.na(clutch_size_max),clutch_size_min,clutch_size_max)
    
    male_mass_mean <- (male_mass_max_g+male_mass_min_g)/2
    female_mass_mean <- (female_mass_min_g+female_mass_max_g)/2
    male_size_mean <- (male_size_min_mm+male_size_max_mm)/2
    female_size_mean <- (female_size_min_mm+female_size_max_mm)/2
    clutch_size_mean <- (clutch_size_min+clutch_size_max)/2
}) %>% select(family,iucn_2021_binomial,Species,elton_bird_name,ends_with('_mean'),egg_volume,nest_type,nest_site,flocking_tendency,Habitat_specificity)
```

```{r}
# # data from reference supplementary material
# amniota <- read.csv("amniota/ECOL_96_269/Data_Files/Amniote_Database_Aug_2015.csv")
# amniota[amniota == -999] <- NA
# amniota$scientificNameStd <- paste(amniota$genus,amniota$species,sep = '_')
# amniota <- filter(amniota,class == "Aves") %>% 
#             select(order,family,scientificNameStd,litter_or_clutch_size_n,egg_mass_g,female_body_mass_g,male_body_mass_g,male_svl_cm,female_svl_cm) %>% 
#                     group_by(scientificNameStd) %>% summarise(litter_or_clutch_size_n = mean(litter_or_clutch_size_n),
#                                                              female_body_mass_g = mean(female_body_mass_g),
#                                                              male_body_mass_g = mean(male_body_mass_g),
#                                                              male_svl_cm = mean(male_svl_cm),
#                                                              female_svl_cm = mean(female_svl_cm))

elton_birds <- read.csv("elton_traits/BirdFuncDat.csv")
elton_birds <- select(elton_birds,Scientific,Nocturnal,BodyMass_Value,starts_with('Diet'),starts_with('ForStrat'))
elton_birds$Scientific <- gsub(" ","_",elton_birds$Scientific)
elton_birds <- elton_birds[!duplicated(elton_birds),]

# bird_behav <- read.csv("Supplementary_Database_from_Integrating_behaviour_and_ecology_into_global_biodiversity_conservation_strategies.csv")
# bird_behav <- select(bird_behav,Species,MatingSystem,NestPlacement,Territoriality,LogClutchSize)
# bird_behav$Species <- gsub(" ","_",bird_behav$Species)
# bird_behav <- bird_behav[!duplicated(bird_behav),]

# Avian_body_sizes <- read.table("Avian_body_sizes_data//avian_ssd_jan07.txt",header = T) %>% select(Species,M_mass,F_mass,Clutch_size,Egg_mass,Mating_System)
# Avian_body_sizes <- Avian_body_sizes[!duplicated(Avian_body_sizes),]
# traits_from_csv <- full_join(Avian_body_sizes, bird_trait_data_ecography,by = 'Species')

# total table contains all information from above data
total <- left_join(Chinesebirdsdata,elton_birds,by = c('Species'='Scientific'))
```

```{r}
name <- filter(total,is.na(ForStrat_ground))$elton_bird_name # use iucn_2021_binomial to merge
addition <- filter(elton_birds,Scientific %in% name) %>% right_join(Chinesebirdsdata, ., by = c('elton_bird_name'='Scientific'))
total_addition <- filter(total,!(elton_bird_name %in% addition$elton_bird_name)) %>% rbind(addition)
total_addition$iucn_2021_binomial <- gsub('_',' ',total_addition$iucn_2021_binomial)
```

## 提取中国鸟类数据集

```{r}
chinese_traits_origin <- filter(total_addition,iucn_2021_binomial %in% Chinese_species_distribution_grid$species,
                                !(family %in% c('Procellariidae','Alcidae','Fregatidae','Gaviidae','Phaethontidae','Diomedeidae',
                                               'Stercorariidae','Sulidae','Pelecanidae','Phalacrocoracidae','Laridae','Hydrobatidae'))) # 筛选出中国陆生鸟类
```

```{r}
filter(chinese_traits_origin,is.na(ForStrat_ground))$iucn_2021_binomial # species not have elton bird data 
```

```{r}
# setdiff(gsub('_',' ',Chinesebirdsdata$iucn_2021_binomial),unique(Chinese_species_distribution_grid$species))
```

```{r}
setdiff(unique(Chinese_species_distribution_grid$species),gsub('_',' ',Chinesebirdsdata$iucn_2021_binomial))
```

```{r}
chinese_traits_origin <- chinese_traits_origin[!duplicated(chinese_traits_origin),]
dupli <- filter(chinese_traits_origin,
       iucn_2021_binomial %in% chinese_traits_origin[duplicated(chinese_traits_origin$iucn_2021_binomial),]$iucn_2021_binomial)
# write.csv(dupli,'dupli.csv',row.names = F)
chinese_traits_origin <- chinese_traits_origin[!duplicated(chinese_traits_origin$iucn_2021_binomial),]
print(paste('鸟类物种数',chinese_traits_origin$iucn_2021_binomial %>% unique() %>% length())) # 包含了一些近年来的新种
```

# 清洗和重编码


## 变量清洗和选取

```{r}
# summary(chinese_traits_origin)
chinese_traits <- within(chinese_traits_origin, {
#     integrate variables' NA
#     Clutch_size_n <- ifelse(Clutch_size_n,litter_or_clutch_size_n,Clutch_size_n)
#     Clutch_size_n <- ifelse(Clutch_size_n,LogClutchSize,Clutch_size_n)
#     Clutch_size_n <- ifelse(Clutch_size_n,Clutch_size,Clutch_size_n)
    # recode
    Diet_5Cat <- dplyr::recode(Diet_5Cat,'FruiNect'=0,'Invertebrate'=1,'Omnivore'=2,'PlantSeed'=3,'VertFishScav'=4)
    # transform categorical variables to factors
    Diet_5Cat <- as.factor(Diet_5Cat)
    Nocturnal <- as.factor(Nocturnal)
    nest_type <- as.factor(nest_type)
    nest_site <- as.factor(nest_site)

}) %>% dplyr::select(-c(family,Species,elton_bird_name,BodyMass_Value,Diet_Source,Diet_Certainty,Diet_EnteredBy,
                        ForStrat_Source,ForStrat_EnteredBy,ForStrat_SpecLevel)) %>%
                          data.table::as.data.table()
summary(chinese_traits)
```

## 填补数据集中的缺失值

```{r}
row.names(chinese_traits) <- gsub(' ','_',chinese_traits$iucn_2021_binomial) # species name as row names
chinese_traits <- dplyr::select(chinese_traits,-c(iucn_2021_binomial))
```

### missMFA方法填补缺失值

```{r}
colnames(chinese_traits)
```

```{r}
# reorder columns
chinese_traits <- dplyr::select(chinese_traits,
                                'female_size_mean','male_size_mean','female_mass_mean','male_mass_mean','egg_volume',
                                'clutch_size_mean',
                                starts_with('Diet_') & !ends_with('5Cat'),
                                starts_with('ForStrat_'),
                                'flocking_tendency',
                                'Habitat_specificity',
                                'nest_site','nest_type',
                                'Nocturnal')
chinese_traits_missmfa <- missMDA::imputeMFA(chinese_traits,group = c(5,1,10,7,1,1,2,1),
                                             type = c(rep('s',6),rep('n',2)))
summary(chinese_traits_missmfa$completeObs)
```

### missForest 方法填补缺失值

```{r}
# # # fill NA by random forest
# chinese_traits_imputed <- missForest::missForest(chinese_traits) # need to delete species name(character)
# summary(chinese_traits_imputed$ximp)
```

# 数据降维


## MFA

```{r}
row.names(chinese_traits_missmfa$completeObs) <- row.names(chinese_traits)
mfa <- FactoMineR::MFA(chinese_traits_missmfa$completeObs,
                       group =c (5,1,10,7,1,1,2,1),
                       type = c(rep('s',6),rep('n',2)),
                       name.group = c('intrinstic_features','Clutch_size','Diets','ForStrat','Society','Habitat_specificity',
                                     'Nest','Nocturnal'),
                       num.group.sup = c(1, 8),
                       ncp = 5)
```

```{r}
library(factoextra)
options(repr.plot.width=9,repr.plot.height=6)
eig.val <- get_eigenvalue(mfa)
fviz_screeplot(mfa,addlabels = TRUE,ncp=15)
ggsave('PCA/screeplot.tiff',height = 5,width = 7,units = 'in',dpi=300)
```

```{r}
options(repr.plot.width=16,repr.plot.height=14)
p1 <- fviz_mfa_var(mfa, "group", labelsize=3, xlim = c(-0.05,0.53)) # the correlation between groups and dimensions. red color = active groups of variables; green color = supplementary groups of variables
p2 <- fviz_mfa_var(mfa, "quanti.var", palette = "jco", 
             col.var.sup = "violet", repel = TRUE, 
            geom = c("point", "text"), legend = "none",labelsize=3) # Correlation between quantitative variables and dimensions
# Contributions to dimension 1
p3 <- fviz_contrib(mfa, choice = "quanti.var", axes = 1, top = 10,
             palette = "jco", labelsize=3, legend = c(0.85,0.8))
# Contributions to dimension 2
p4 <- fviz_contrib(mfa, choice = "quanti.var", axes = 2, top = 10,
             palette = "jco", labelsize=3, legend = c(0.85,0.8))
ggpubr::ggarrange(p1,p2,p3,p4,ncol = 2,nrow = 2)
ggsave('PCA/pca_dimensions.tiff',height = 9,width = 10,units = 'in',dpi=300)
```

```{r}
# functional distribution of individual species. Individuals with similar profiles are close to each other on the factor map
options(repr.plot.width=14,repr.plot.height=12)
fviz_mfa_ind(mfa, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE,legend = c(0.85,0.85))
ggsave('PCA/species_space.tiff',height = 10,width = 10,units = 'in',dpi=300)
```

```{r}
ind_mfa <- get_mfa_ind(mfa)$coord # 提取主成分
head(ind_mfa)
write.csv(ind_mfa,'ind_mfa.csv')
```

```{r}
row.names(ind_mfa) <- gsub(' ','_',row.names(ind_mfa))
Chinese_species_distribution_grid$species <- gsub(' ','_',Chinese_species_distribution_grid$species)
```

# 计算功能多样性


## function

```{r}
FD_calculate <- function(grid_id,ind_pca,Chinese_species_distribution_grid_selected){
    grid_table <- subset(Chinese_species_distribution_grid_selected,rownames(Chinese_species_distribution_grid_selected)==grid_id)
    grid_table <- subset(grid_table,select=colnames(grid_table)[colSums(grid_table)!=0])
    species <- colnames(grid_table)
    ind_pca_table <- subset(ind_pca,rownames(ind_pca) %in% species)
    tryCatch({
        FD <- FD::dbFD(ind_pca_table,grid_table)
        result <- data.frame(grid_id,FD$FRic,FD$FEve,FD$FDiv,FD$FDis,FD$RaoQ)
        return(result)
    },error = function(e){
        return(data.frame())
    })
}
```

## total

```{r}
# # distribution data
#long table to wide table
Chinese_species_distribution_grid_selected <- filter(
                                                    Chinese_species_distribution_grid,
                                                    species %in% unique(row.names(ind_mfa))
                                                    ) %>% 
                                              dplyr::select(grid_id,species)
Chinese_species_distribution_grid_selected$occurrence <- rep(1,nrow(Chinese_species_distribution_grid_selected))
Chinese_species_distribution_grid_selected <- spread(Chinese_species_distribution_grid_selected,species,occurrence) 

# to matrix
Chinese_species_distribution_grid_selected[is.na(Chinese_species_distribution_grid_selected)] <- 0
Chinese_species_distribution_grid_selected <- dplyr::select(Chinese_species_distribution_grid_selected, grid_id,row.names(ind_mfa)) %>% data.matrix()
row.names(Chinese_species_distribution_grid_selected) <- as.character(Chinese_species_distribution_grid_selected[,'grid_id'])
Chinese_species_distribution_grid_selected <- Chinese_species_distribution_grid_selected[,-1]
nrow(Chinese_species_distribution_grid_selected) # sites that has mammal
```

```{r}
nrow(ind_mfa)==ncol(Chinese_species_distribution_grid_selected)
```

```{r}
# grid_id <- row.names(Chinese_species_distribution_grid_selected)

# library(foreach)
# library(doParallel)
# print(paste0('CPUs_used:',40))
# cl <- makeCluster(40)
# registerDoParallel(cl)
# FD_total <- foreach(
#     i = grid_id,
#     .combine = rbind,
#     .packages = c("FD","dplyr"),
#     .export = c('ind_mfa','Chinese_species_distribution_grid_selected')
# ) %dopar% FD_calculate(i,ind_mfa,Chinese_species_distribution_grid_selected)
# stopCluster(cl)
# write.csv(FD_total,"FD_bird_total.csv",row.names=F)
```

```{r}
FD_total <- read.csv('FD_bird_total.csv')
```

```{r}
phyloregion_multicompare <- function(df,var){
    region_df <- read.csv('../phyloregion_df.csv') %>%mutate_at('grids',as.character)
    realm_tmp <- df %>% mutate_at('grid_id',as.character) %>% left_join(region_df,by = c('grid_id'='grids')) %>% 
        mutate(realms=case_when(cluster %in% c(1,9,12) ~ 'North',
                               cluster %in% c(2,3,4,5,7,8) ~ 'West',
                               cluster %in% c(6,10,11,13,14,15) ~ 'South')) %>% mutate_at('realms',as.factor)
    realm_tmp <- realm_tmp[which(!is.na(realm_tmp[var])),]
    fml <- as.formula("realm_tmp[[var]]~realm_tmp[['realms']]")
    fit <- aov(fml)
    return(TukeyHSD(fit))
}
```

```{r}
phyloregion_multicompare(FD_total,'FD.FRic')
phyloregion_multicompare(FD_total,'FD.FDiv')
phyloregion_multicompare(FD_total,'FD.FEve')
```

```{r}
grid <- st_read("../chinese_terrestral//input//grid.shp")
FD_total_map <- left_join(FD_total,grid,by = c('grid_id'='id'))

options(repr.plot.width=12, repr.plot.height=10)
ggplot()+geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = FD_total_map,aes(fill = FD.FRic,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=divider,size = divider))+
    scale_color_manual(values = c('grey60','red','#F75404'),guide = "none")+ # delete legends of divider
    scale_size_manual(values = c(0.5,0.8,0.6),guide = "none")+
    ggtitle("FRic")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5),
         legend.position = c(0.13,0.2),
         legend.key.size = unit(18, "pt"),
         legend.title=element_text(size=13),
         legend.text=element_text(size=10))
ggsave('bird_FRic.tiff',height = 7,width = 7,units = 'in' ,dpi=300)
ggplot()+geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = filter(FD_total_map,!is.na(FD.FDiv)),aes(fill = FD.FDiv,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=divider,size = divider))+
    scale_color_manual(values = c('grey60','red','#F75404'),guide = "none")+ # delete legends of divider
    scale_size_manual(values = c(0.5,0.8,0.6),guide = "none")+
    ggtitle("FD.FDiv")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5),
         legend.position = c(0.13,0.2),
         legend.key.size = unit(18, "pt"),
         legend.title=element_text(size=13),
         legend.text=element_text(size=10))
ggsave('bird_FDiv.tiff',height = 7,width = 7,units = 'in' ,dpi=300)
ggplot()+geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = filter(FD_total_map,!is.na(FD.FEve)),aes(fill = FD.FEve,geometry = geometry),colour='white',alpha=0.8,size=0)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    geom_sf(data = phyloregions_line,aes(geometry = geometry,col=divider,size = divider))+
    scale_color_manual(values = c('grey60','red','#F75404'),guide = "none")+ # delete legends of divider
    scale_size_manual(values = c(0.5,0.8,0.6),guide = "none")+
    ggtitle("FD.FEve")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5),
         legend.position = c(0.13,0.2),
         legend.key.size = unit(18, "pt"),
         legend.title=element_text(size=13),
         legend.text=element_text(size=10))
ggsave('bird_FEve.tiff',height = 7,width = 7,units = 'in' ,dpi=300)
```

## body and egg size

```{r}
intrinstic_features <- dplyr::select(chinese_traits_missmfa$completeObs,contains('male'),'egg_volume') %>% na.omit()
# PCA
options(repr.plot.width=4,repr.plot.height=5)
# paran::paran(mass,iterations = 5000) # Horn's method for massermining the number of retaining principal components
princomp <- princomp(intrinstic_features,cor = T)
pca_var <- get_pca_var(princomp)
p1 <- fviz_screeplot(princomp)
# Contributions to dimension 1
p2 <- fviz_contrib(princomp, choice = "var", axes = 1, top = 20,
             palette = "jco")
# Contributions to dimension 2
p3 <- fviz_contrib(princomp, choice = "var", axes = 2, top = 20,
             palette = "jco")
# Plot together
ggpubr::ggarrange(p1,p2,p3,ncol = 3,nrow = 1)
# functional distribution of individual species. Individuals with similar profiles are close to each other on the factor map
options(repr.plot.width=16,repr.plot.height=13)
fviz_pca_ind(princomp, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)

ind_pca <- get_pca_ind(princomp)$coord[,1:2] %>% as.data.frame()

# # distribution data
#long table to wide table
Chinese_species_distribution_grid_selected <- filter(
                                                    Chinese_species_distribution_grid,
                                                    species %in% unique(row.names(ind_pca))
                                                    ) %>% 
                                              dplyr::select(grid_id,species)
Chinese_species_distribution_grid_selected$occurrence <- rep(1,nrow(Chinese_species_distribution_grid_selected))
Chinese_species_distribution_grid_selected <- spread(Chinese_species_distribution_grid_selected,species,occurrence) 
Chinese_species_distribution_grid_selected[is.na(Chinese_species_distribution_grid_selected)] <- 0

# to matrix
Chinese_species_distribution_grid_selected <- dplyr::select(Chinese_species_distribution_grid_selected, 'grid_id', row.names(ind_pca)) %>% 
                                                        as.matrix()
row.names(Chinese_species_distribution_grid_selected) <- Chinese_species_distribution_grid_selected[,1]
Chinese_species_distribution_grid_selected <- Chinese_species_distribution_grid_selected[,-1]
nrow(Chinese_species_distribution_grid_selected) # sites that has species
```

```{r}
grid_id <- row.names(Chinese_species_distribution_grid_selected)

library(foreach)
library(doParallel)
print(paste0('CPUs_used:',40))
cl <- makeCluster(40)
registerDoParallel(cl)
FD_body_size <- foreach(
    i = grid_id,
    .combine = rbind,
    .packages = c("FD","dplyr"),
    .export = c('ind_pca','Chinese_species_distribution_grid_selected')
) %dopar% FD_calculate(i,ind_pca,Chinese_species_distribution_grid_selected)
stopCluster(cl)
colnames(FD_body_size) <- c("grid_id","FD_body_size.FRic","FD_body_size.FEve","FD_body_size.FDiv",
                            "FD_body_size.FDis","FD_body_size.RaoQ")
write.csv(FD_body_size,"FD_bird_body_size.csv",row.names=F)
```

```{r}
ind_pca$species <- row.names(ind_pca)
body_size <- left_join(ind_pca,Chinese_species_distribution_grid,by = 'species')
body_size_mean <- group_by(body_size,grid_id) %>% summarise(body_size_mean = mean(Dim.1),body_size_sd = sd(Dim.1))
write.csv(body_size_mean,'bird_body_size_mean')
body_size_mean_map <- left_join(body_size_mean, grid, by = c('grid_id'='id'))
ggplot()+geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = body_size_mean_map,aes(fill = body_size_mean,geometry = geometry),colour='white',alpha=0.8,size=0.05)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    ggtitle("body_size_mean")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5))
```

```{r}
FD_body_size <- read.csv('FD_bird_body_size.csv')
FD_body_size <- apply(FD_body_size,2,as.numeric) %>% as.data.frame()
FD_body_size_map <- left_join(FD_body_size, grid, by = c('grid_id'='id'))
ggplot()+geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = FD_body_size_map,aes(fill = FD.FRic,geometry = geometry),colour='white',alpha=0.8,size=0.05)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    ggtitle("body_size_FRic")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5))
```

## diet

```{r}
diet <- dplyr::select(chinese_traits,starts_with('Diet_') & !ends_with('5Cat')) %>% filter(!is.na(Diet_Inv))
rownm <- row.names(diet)
diet <- as.data.frame(diet)
row.names(diet) <- rownm
# PCA
options(repr.plot.width=4,repr.plot.height=5)
# paran::paran(mass,iterations = 5000) # Horn's method for massermining the number of retaining principal components
princomp <- princomp(diet,cor = T)
pca_var <- get_pca_var(princomp)
p1 <- fviz_screeplot(princomp)
# Contributions to dimension 1
p2 <- fviz_contrib(princomp, choice = "var", axes = 1, top = 20,
             palette = "jco")
# Contributions to dimension 2
p3 <- fviz_contrib(princomp, choice = "var", axes = 2, top = 20,
             palette = "jco")
# Plot together
ggpubr::ggarrange(p1,p2,p3,ncol = 3,nrow = 1)
# functional distribution of individual species. Individuals with similar profiles are close to each other on the factor map
options(repr.plot.width=16,repr.plot.height=13)
fviz_pca_ind(princomp, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)

ind_pca <- get_pca_ind(princomp)$coord[,1:5] %>% as.data.frame()

# # distribution data
#long table to wide table
Chinese_species_distribution_grid_selected <- filter(
                                                    Chinese_species_distribution_grid,
                                                    species %in% unique(row.names(ind_pca))
                                                    ) %>% 
                                              dplyr::select(grid_id,species)
Chinese_species_distribution_grid_selected$occurrence <- rep(1,nrow(Chinese_species_distribution_grid_selected))
Chinese_species_distribution_grid_selected <- spread(Chinese_species_distribution_grid_selected,species,occurrence) 
Chinese_species_distribution_grid_selected[is.na(Chinese_species_distribution_grid_selected)] <- 0

# to matrix
Chinese_species_distribution_grid_selected <- dplyr::select(Chinese_species_distribution_grid_selected, 'grid_id', row.names(ind_pca)) %>% 
                                                        as.matrix()
row.names(Chinese_species_distribution_grid_selected) <- Chinese_species_distribution_grid_selected[,1]
Chinese_species_distribution_grid_selected <- Chinese_species_distribution_grid_selected[,-1]
nrow(Chinese_species_distribution_grid_selected) # sites that has species
```

```{r}
grid_id <- row.names(Chinese_species_distribution_grid_selected)

library(foreach)
library(doParallel)
print(paste0('CPUs_used:',40))
cl <- makeCluster(40)
registerDoParallel(cl)
FD_diet <- foreach(
    i = grid_id,
    .combine = rbind,
    .packages = c("FD","dplyr"),
    .export = c('ind_pca','Chinese_species_distribution_grid_selected')
) %dopar% FD_calculate(i,ind_pca,Chinese_species_distribution_grid_selected)
stopCluster(cl)
colnames(FD_diet) <- c("grid_id","FD_diet.FRic","FD_diet.FEve","FD_diet.FDiv",
                            "FD_diet.FDis","FD_diet.RaoQ")

write.csv(FD_diet,"FD_bird_diet.csv",row.names=F)
```

```{r}
FD_diet <- read.csv('FD_bird_diet.csv') %>% apply(2,as.numeric) %>% as.data.frame()
FD_diet_map <- left_join(FD_diet, grid, by = c('grid_id'='id'))
ggplot()+geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = FD_diet_map,aes(fill = FD.FRic,geometry = geometry),colour='white',alpha=0.8,size=0.05)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    ggtitle("diet_FRic")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5))
```

## ForStrat

```{r}
ForStrat <- dplyr::select(chinese_traits, starts_with('ForStrat_')) %>% filter(!is.na(ForStrat_watbelowsurf))
rownm <- row.names(ForStrat)
ForStrat <- as.data.frame(ForStrat)
row.names(ForStrat) <- rownm
# PCA
# paran::paran(mass,iterations = 5000) # Horn's method for massermining the number of retaining principal components
princomp <- princomp(ForStrat,cor = T)
pca_var <- get_pca_var(princomp)
options(repr.plot.width=4,repr.plot.height=5)
p1 <- fviz_screeplot(princomp)
# Contributions to dimension 1
p2 <- fviz_contrib(princomp, choice = "var", axes = 1, top = 20,
             palette = "jco")
# Contributions to dimension 2
p3 <- fviz_contrib(princomp, choice = "var", axes = 2, top = 20,
             palette = "jco")
# Plot together
options(repr.plot.width=16,repr.plot.height=6)
ggpubr::ggarrange(p1,p2,p3,ncol = 3,nrow = 1)
# functional distribution of individual species. Individuals with similar profiles are close to each other on the factor map
options(repr.plot.width=15,repr.plot.height=12)
fviz_pca_ind(princomp, col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)

ind_pca <- get_pca_ind(princomp)$coord[,1:3]

# # distribution data
#long table to wide table
Chinese_species_distribution_grid_selected <- filter(
                                                    Chinese_species_distribution_grid,
                                                    species %in% unique(row.names(ind_pca))
                                                    ) %>% 
                                              dplyr::select(grid_id,species)
Chinese_species_distribution_grid_selected$occurrence <- rep(1,nrow(Chinese_species_distribution_grid_selected))
Chinese_species_distribution_grid_selected <- spread(Chinese_species_distribution_grid_selected,species,occurrence) 
Chinese_species_distribution_grid_selected[is.na(Chinese_species_distribution_grid_selected)] <- 0

# to matrix
Chinese_species_distribution_grid_selected <- dplyr::select(Chinese_species_distribution_grid_selected, 'grid_id', row.names(ind_pca)) %>% 
                                                        as.matrix()
row.names(Chinese_species_distribution_grid_selected) <- Chinese_species_distribution_grid_selected[,1]
Chinese_species_distribution_grid_selected <- Chinese_species_distribution_grid_selected[,-1]
nrow(Chinese_species_distribution_grid_selected) # sites that has species
```

```{r}
grid_id <- row.names(Chinese_species_distribution_grid_selected)

library(foreach)
library(doParallel)
print(paste0('CPUs_used:',40))
cl <- makeCluster(40)
registerDoParallel(cl)
FD_ForStrat <- foreach(
    i = grid_id,
    .combine = rbind,
    .packages = c("FD","dplyr"),
    .export = c('ind_pca','Chinese_species_distribution_grid_selected')
) %dopar% FD_calculate(i,ind_pca,Chinese_species_distribution_grid_selected)
stopCluster(cl)
colnames(FD_ForStrat) <- c("grid_id","FD_ForStrat.FRic","FD_ForStrat.FEve","FD_ForStrat.FDiv",
                            "FD_ForStrat.FDis","FD_ForStrat.RaoQ")
write.csv(FD_ForStrat,"FD_bird_ForStrat.csv",row.names=F)
```

```{r}
FD_ForStrat <- read.csv('FD_bird_ForStrat.csv')
FD_ForStrat_map <- left_join(FD_ForStrat, grid, by = c('grid_id'='id'))
ggplot()+geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = FD_ForStrat_map,aes(fill = FD.FRic,geometry = geometry),colour='white',alpha=0.8,size=0.05)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    ggtitle("ForStrat_FRic")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5))
```

 ## clutch size

```{r}
clutch_size <- dplyr::select(chinese_traits, 'clutch_size_mean') %>% 
                    filter(!is.na(clutch_size_mean))
clutch_size$species <- row.names(clutch_size)
clutch_size <- left_join(clutch_size,Chinese_species_distribution_grid,by = 'species')
clutch_size_mean <- group_by(clutch_size,grid_id) %>% summarise(clutch_size_grid_mean = mean(clutch_size_mean),clutch_size_sd = sd(clutch_size_mean))
write.csv(clutch_size_mean,"FD_bird_clutch_size.csv",row.names=F)
clutch_size_mean_map <- left_join(clutch_size_mean, grid, by = c('grid_id'='id'))
ggplot()+geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = clutch_size_mean_map,aes(fill = clutch_size_grid_mean,geometry = geometry),colour='white',alpha=0.8,size=0.05)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    ggtitle("clutch_size_mean")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5))
ggplot()+geom_sf(data = china_map,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = south_ocean,aes(geometry = geometry),colour='grey60',fill='grey90',size=0.2)+
    geom_sf(data = clutch_size_mean_map,aes(fill = clutch_size_sd,geometry = geometry),colour='white',alpha=0.8,size=0.05)+
    scale_fill_distiller(palette = "Spectral")+ # fill 
    ggtitle("clutch_size_sd")+
    theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.title = element_text(hjust = 0.5))
```

# cwm

```{r}
cwm <- FD::functcomp(ind_mfa,Chinese_species_distribution_grid_selected) %>% dplyr::select(Dim.1,Dim.2) %>% 
            tibble::rownames_to_column('id')
```

```{r}
cwm_table <- read.csv("../environment_variables.csv") %>% 
                dplyr::select(id, prec, tavg, LGM_tavg_velocity,dem_value) %>% as.data.frame() %>% 
                        dplyr::mutate_at(vars(contains('id')),as.character) %>% left_join(cwm,by = 'id')
```

```{r}
lm_eqn <- function(m){
  eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2~", p ="~p, 
                   list(a = format(unname(coef(m)[1]), digits = 2),
                        b = format(unname(coef(m)[2]), digits = 2),
                        r2 = format(summary(m)$r.squared, digits = 3),
                        p = format(summary(m)$coef[2,4], digits = 2)))
  as.character(as.expression(eq));
}
```

```{r}
options(repr.plot.width=10,repr.plot.height=10)
m1 <- lm(Dim.1~LGM_tavg_velocity,cwm_table)
f1 <- ggplot(data = cwm_table,aes(x = LGM_tavg_velocity,y = Dim.1))+geom_point()+
            geom_smooth(method = "lm")+theme_bw()+ 
                  geom_text(x = 30, y = -0.2, label = lm_eqn(m1), parse = TRUE)
cwm_p1 <- ggpubr::annotate_figure(f1,fig.lab = "A",fig.lab.size = 18)

m2 <- lm(Dim.2~LGM_tavg_velocity,cwm_table)
f2 <- ggplot(data = cwm_table,aes(x = LGM_tavg_velocity,y = Dim.2))+geom_point()+
            geom_smooth(method = "lm")+theme_bw()+ 
                  geom_text(x = 30, y = 0.58, label = lm_eqn(m2), parse = TRUE)
cwm_p2 <- ggpubr::annotate_figure(f2,fig.lab = "B",fig.lab.size = 18)

ggpubr::ggarrange(cwm_p1,cwm_p2,ncol = 1,nrow = 2)
ggsave('PCA/cwm_lm.tiff',height = 10,width = 10,units = 'in',dpi=300)
```

```{r}

```
