---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.13.0
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(tidyverse)
library(ape)
```

# constraint tree

```{r}
fasta <- read.FASTA("../01.alignment/six_gene.fasta")
taxa_table <- as.data.frame(names(fasta))
colnames(taxa_table) <- 'taxa'
```

```{r}
taxa_table <- tidyr::separate(taxa_table,taxa,into = c("class","order","family","genus","species"),sep = "_",remove = F)
taxa_table$binomial <- paste(taxa_table$genus,taxa_table$species,sep = '_')
```

```{r}
phy <- read.tree('tree2/tetrapod_conglomerate_tree')
splist <- strsplit(phy$tip.label,split='_') %>% sapply(function(x){paste(x[1],x[2],sep='_')})
tetrapod <- data.frame(phy$tip.label,splist)
head(tetrapod)
```

```{r}
inter_tb <- inner_join(taxa_table,tetrapod,by =c('binomial'='splist'))
phy_keep <- keep.tip(phy, inter_tb$phy.tip.label)
phy_keep$tip.label <- inter_tb[match(phy_keep$tip.label,inter_tb$phy.tip.label),]$taxa
```

```{r}
# write.tree(phy_keep, file = "tree2/tetrapod_conglomerate_tree.keep")
```

```{r}
dplyr::select(taxa_table,binomial) %>% write.table('six_gene_phy_taxa.txt',,sep='\t',row.names = F,quote=F,col.names=F)
```

# fossil time

```{r}
fossil <- read.table('./timetree_table.txt',sep = '\t',col.names = c('binomial','min','max','node'))
fossil <- left_join(fossil,taxa_table,by = 'binomial') %>% select('taxa','min','max','node')
```

```{r}
node.no <- which(!is.na(fossil$node))
result <- c()
for (i in 1:length(node.no)){
    if (i != length(node.no)){
        splist <- paste(fossil$taxa[node.no[i]:(node.no[i+1]-1)],collapse = ' ')
    } else {
        splist <- paste(fossil$taxa[node.no[i]:length(fossil$taxa)],collapse = ' ')
    }
    
    first_line <- paste('mrca =',fossil$node[node.no[i]],splist,sep = ' ')
    second_line <- paste('min =',fossil$node[node.no[i]],fossil$min[node.no[i]],sep = ' ')
    third_line <- paste('max =',fossil$node[node.no[i]],fossil$max[node.no[i]],sep = ' ')
    result <- append(result,first_line) %>% append(second_line) %>% append(third_line)
}
```

```{r}
tree <- read.tree('tree2/tree2.treefile')
fossil$node <- zoo::na.locf(fossil$node)
mrca_node <- tapply(fossil$taxa,fossil$node,function(x) ape::getMRCA(tree,x)) %>% as.data.frame()
```

```{r}
write.table(as.data.frame(result),'timetree_table_long.txt',col.names=F,row.names=F,quote=F)
```
